// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://qiwphwptypshrlhxqqzu.supabase.co";
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

export const supabase = createClient<Database>(SUPABASE_URL || "https://qiwphwptypshrlhxqqzu.supabase.co", SUPABASE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpd3Bod3B0eXBzaHJsaHhxcXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NjQ4OTcsImV4cCI6MjA4OTU0MDg5N30._tATVdCpIbio0qMfBiEoxiivI8B8MAJ4eBRy8hQjL2A", {
  auth: { storage: localStorage, persistSession: true, autoRefreshToken: true },
});